before_script:
- npm install -g grunt-cli
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
  - secure: EAAejPpw+v+ooM5HQdRbQTSW85aAyKB51ADc30GnpD2TP4Cw8RgWHkYqEFm47X65b9UeZLp5CwzqWk9+QvTg09jloowvrLPCCEE+VznKx10Sb/chd0y9Dcg8L9vEUeWC2WKsL+xVMfsGyu3rILWWgvK5S3RH/C2n44X4ADa1doc=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  on:
    all_branches: true
    tags: true
  api_key:
    secure: BKgTHGK2rBR5tWZ/7VSlyi+t0ttmFUyHbFv8t6pAMuvHC/TdZWQTGddosNsYLO5njTj9z4OHVz+/B8ESKcGHKAVjYPwdGSIMTgs8xXcG8FksTrKfwhTxckgYdPu2SghVkjczbJ3Frmn2KXxHWLpFepn52IIpyxTwUVw3VdGCTcg=
