before_script:
- npm install -g grunt-cli
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
    secure: cPsGsdJ58fR08F9kYHZewwx1vBHLodfV8MuKWOAyhoFHz14tJHR+IDXU1K1OeFtEiDe1KyzTmq4Qul5O5EuGvLbhJLopD05dwZfVsndSfV2726vtfcSZKJ0cbd06JxTpP911Ft8Eipz7tMT99aBKj9OPwhQmKdz7tqq1MWTemC4=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  api_key:
    secure: fF1ptoYbAXEOCmr++jjkD7tcChciqiM83nyoaQyIW2fuZRvSxXsO9C4enG/7aQ1F1eNb0wepwrBeqGb1mhT7fKEswoeTA3RREhnKU596gwLpzqzCzZW48lUHM94zd3r3hpl4WP3aH4ZAr2Gh3+O5TpoyUfiHXPhVqXuWmC0bSQs=
  on:
    all_branches: true
    tags: true
